#!/usr/bin/env bash
# Time the loop a developer (or an agent) is actually in: change code, run the
# tests, read the result, change code again.
#
# `make test` on an untouched tree measures the tests. It does not measure the
# thing you spend your day doing, because every real iteration pays a rebuild
# first — and a rebuild is exactly what a profile change can make *worse* while
# the test-execution number gets better. Measuring only the warm case would hide
# that trade entirely.
#
# Four scenarios, cheapest to most expensive:
#
#   rerun      nothing changed — the floor
#   test-edit  a test file changed; one test binary recompiles and relinks
#   leaf-edit  a library everything depends on changed
#   bin-edit   the 11k-line CLI binary changed
#
#   .shux/scripts/bench_edit_loop.sh
#   RUNS=3 .shux/scripts/bench_edit_loop.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${REPO_ROOT}"

RUNS="${RUNS:-2}"
OUT_DIR="${OUT_DIR:-${REPO_ROOT}/.shux/out/issue-130}"
LABEL="${LABEL:-$(uname -s)-$(uname -m)}"
mkdir -p "${OUT_DIR}"

runtime_dir="$(mktemp -d "/tmp/shux-loop.XXXXXX")"
export XDG_RUNTIME_DIR="${runtime_dir}"
cleanup() {
  rm -rf "${runtime_dir}"
}
trap cleanup EXIT

# NOTE: this script only ever `touch`es files — it changes mtimes to force a
# recompile and never changes a byte of content, so there is nothing to undo.
#
# An earlier version "cleaned up" with `git checkout -- <the touched files>`,
# which is not a no-op on a working tree with uncommitted edits: it silently
# reverted them. It destroyed a test rewrite mid-session, and the next run then
# measured a stale binary and reported failures for a defect that had already
# been fixed. A benchmark must not be able to modify the thing it measures.
#
# If you add a scenario that genuinely edits content, write to a scratch copy —
# do not reach for `git checkout` in a trap.

# Warm everything first. The first build after a fresh clone is a different
# question with a different answer, and averaging it in here would swamp the
# signal we are after.
echo "▶ Warming the build (not measured)..."
cargo test --workspace --no-run >/dev/null 2>&1

report="${OUT_DIR}/edit-loop-${LABEL}.md"
{
  echo "# Edit → test loop — ${LABEL}"
  echo
  echo "Wall-clock for \`make test\` after each kind of change. ${RUNS} runs each,"
  echo "best reported (the loop's floor is what you feel; a scheduling hiccup is not"
  echo "a property of the change)."
  echo
  echo "| Scenario | What changed | Best | Runs |"
  echo "|---|---|---|---|"
} > "${report}"

scenario() {
  local name="$1" desc="$2" mutate="$3"
  local best="" all=""
  for _ in $(seq 1 "${RUNS}"); do
    eval "${mutate}"
    local s e d
    s="$(date +%s.%N)"
    if ! make test >/tmp/shux-loop.log 2>&1; then
      echo "  ✗ ${name}: make test FAILED — see /tmp/shux-loop.log" >&2
      tail -20 /tmp/shux-loop.log >&2
      exit 1
    fi
    e="$(date +%s.%N)"
    d="$(echo "${e} - ${s}" | bc)"
    all="${all} $(printf '%.1f' "${d}")"
    if [[ -z "${best}" ]] || (( $(echo "${d} < ${best}" | bc -l) )); then best="${d}"; fi
  done
  printf "  %-11s %6.1fs   (%s)\n" "${name}" "${best}" "${all# }"
  printf "| \`%s\` | %s | %.1f s | %s |\n" "${name}" "${desc}" "${best}" "${all# }" >> "${report}"
}

echo "▶ Measuring (${RUNS} runs per scenario)..."

scenario rerun     "nothing"                         "true"
scenario test-edit "a test file"                     "touch crates/shux-vt/tests/scroll_region_bounds.rs"
scenario leaf-edit "shux-vt/src/lib.rs (core lib)"   "touch crates/shux-vt/src/lib.rs"
scenario bin-edit  "shux/src/main.rs (11k-line CLI)" "touch crates/shux/src/main.rs"

echo >> "${report}"
echo "Generated by \`.shux/scripts/bench_edit_loop.sh\`." >> "${report}"

echo
echo "✓ ${report}"
